"""
Django settings for Mind project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_flag(name, default):
    """Ortam degiskenini bayrak olarak oku; tanimsizsa `default`."""
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name):
    """Virgulle ayrilmis ortam degiskenini listeye cevir; bos ogeleri atar."""
    return [item.strip() for item in os.environ.get(name, '').split(',') if item.strip()]


# Gelistirme anahtari depoda oldugu icin gizli degil; uretimde
# DJANGO_SECRET_KEY zorunlu (asagidaki kontrole bak).
DEV_SECRET_KEY = 'django-insecure-7s3phjir9f5im-2hqsr3suk58vw4h^p@-o47a+&eojj80u-)k2'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', DEV_SECRET_KEY)

DEBUG = env_flag('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS')

# Uretimde eksik ayarla sessizce guvensiz calismaktansa aciliste durmak
# yeglenir; asagidaki iki hata da ilk istegi degil, konteyneri dusurur.
if not DEBUG:
    if SECRET_KEY == DEV_SECRET_KEY:
        raise ImproperlyConfigured(
            'DJANGO_DEBUG kapaliyken DJANGO_SECRET_KEY tanimlanmali. '
            'Depodaki gelistirme anahtari herkese acik oldugu icin '
            'oturum ve parola sifirlama jetonlari taklit edilebilir. '
            'Uret: python -c "from django.core.management.utils import '
            'get_random_secret_key as k; print(k())"'
        )
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            'DJANGO_DEBUG kapaliyken DJANGO_ALLOWED_HOSTS tanimlanmali '
            '(orn. "mind.ornek.com,192.0.2.10").'
        )

AUTH_USER_MODEL="Accounts.AppUser"
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Accounts.apps.AccountsConfig',
    'ExpenseTracker.apps.ExpensetrackerConfig',
    'CareerPath.apps.CareerpathConfig',
    'Notebook.apps.NotebookConfig',
    'rest_framework',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Mind.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Mind.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'mind-db'),
        'USER': os.environ.get('POSTGRES_USER', 'cerberus'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'cerberus'),
        # Varsayilan, compose agindaki servis adi; host makineden calisirken
        # POSTGRES_HOST=127.0.0.1 vermek yeterli.
        'HOST': os.environ.get('POSTGRES_HOST', 'postgresql-database'),
        'PORT': int(os.environ.get('POSTGRES_PORT', '5432')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Authentication
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'accounts:index'


# Uretim sertlestirmesi
# https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

if not DEBUG:
    # nginx `X-Forwarded-Proto`yu kendisi yaziyor; Django istegin disaridan
    # https ile geldigini ancak boyle bilebilir.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

    # TLS acilana kadar kapali kalmali: cerezleri "yalniz https" isaretlemek
    # duz http'de oturum acmayi imkansiz kilar, SSL yonlendirmesi de sonsuz
    # donguye sokar.
    HTTPS_ENABLED = env_flag('DJANGO_HTTPS', False)
    SESSION_COOKIE_SECURE = HTTPS_ENABLED
    CSRF_COOKIE_SECURE = HTTPS_ENABLED
    SECURE_SSL_REDIRECT = HTTPS_ENABLED
    SECURE_HSTS_SECONDS = 31536000 if HTTPS_ENABLED else 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = HTTPS_ENABLED
    SECURE_HSTS_PRELOAD = HTTPS_ENABLED
