# Generated by Django 6.0.1 on 2026-01-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_appuser_phone_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='profile_avatars', verbose_name='user_avatar'),
        ),
    ]
