# Generated by Django 6.0.1 on 2026-02-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debts',
            name='remaining_installments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='debts',
            name='total_installments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='debts',
            name='cutoff_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
