# Generated by Django 6.0.1 on 2026-02-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0003_remove_debts_installment_fields'),
    ]

    operations = [
        # Fields already removed by 0003 via RunSQL DROP COLUMN IF EXISTS
    ]
