# Generated by Django 6.0.1 on 2026-02-17 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0006_remove_debts_remaining_installments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='credits',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='credits',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bank_debts', to='ExpenseTracker.banks'),
        ),
        migrations.AlterUniqueTogether(
            name='credits',
            unique_together={('user', 'bank', 'cutoff_date')},
        ),
    ]
