# Generated by Django 6.0.1 on 2026-02-17 20:33

import django.db.models.deletion
from django.db import migrations, models


def add_start_date_if_missing(apps, schema_editor):
    """Add start_date column only if it doesn't exist yet."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = 'ExpenseTracker_credits' AND column_name = 'start_date'
        """)
        if not cursor.fetchone():
            cursor.execute('ALTER TABLE "ExpenseTracker_credits" ADD COLUMN "start_date" date NULL')


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0007_alter_credits_unique_together_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='credits',
                    name='start_date',
                    field=models.DateField(blank=True, null=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_start_date_if_missing, migrations.RunPython.noop),
            ],
        ),
        migrations.CreateModel(
            name='CreditInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='ExpenseTracker.credits')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('credit', 'installment_number')},
            },
        ),
    ]
