# Generated by Django 6.0.1 on 2026-06-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ExpenseTracker", "0009_remove_debts_remaining_installments_and_more"),
    ]

    operations = [
        # Drop the unwanted unique constraint on (user, total_debt, bank) so a
        # user can record multiple debts with the same amount at the same bank.
        migrations.AlterUniqueTogether(
            name="debts",
            unique_together=set(),
        ),
        # These two columns were already dropped from the database in an earlier
        # change, but the migration state still tracked them. Sync the state only
        # (no database operation) to avoid a "column does not exist" error.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="debts",
                    name="remaining_installments",
                ),
                migrations.RemoveField(
                    model_name="debts",
                    name="total_installments",
                ),
            ],
            database_operations=[],
        ),
    ]
