# Generated by Django 6.0.1 on 2026-07-27 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ExpenseTracker", "0010_alter_debts_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="debts",
            constraint=models.UniqueConstraint(
                fields=("user", "bank", "cutoff_date"),
                name="uniq_debt_per_bank_and_cutoff",
                nulls_distinct=False,
            ),
        ),
    ]
