# Generated by Django 6.0.1 on 2026-07-27 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ExpenseTracker", "0011_debts_uniq_debt_per_bank_and_cutoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="banks",
            name="card_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Bos birakilirsa doluluk gostergesi gizlenir.",
                max_digits=12,
                null=True,
                verbose_name="Kart Limiti",
            ),
        ),
        migrations.AddField(
            model_name="banks",
            name="statement_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Bos birakilirsa son ekstrenin gununden turetilir.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
                verbose_name="Hesap Kesim Gunu",
            ),
        ),
    ]
