# Generated by Django 6.0.1 on 2026-07-27 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ExpenseTracker", "0012_banks_card_limit_banks_statement_day"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="card",
            field=models.ForeignKey(
                blank=True,
                help_text="Yalnizca kredi kartiyla yapilan harcamalarda dolu olur.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="card_expenses",
                to="ExpenseTracker.banks",
                verbose_name="Kredi Kartı",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Nakit"), ("credit", "Kredi Kartı")],
                default="cash",
                max_length=8,
                verbose_name="Ödeme Yöntemi",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("card__isnull", False), ("payment_method", "credit")),
                    models.Q(("card__isnull", True), ("payment_method", "cash")),
                    _connector="OR",
                ),
                name="expense_card_matches_payment_method",
            ),
        ),
    ]
