# Generated by Django 6.0.1 on 2026-05-16 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Tema anahtarı, örn 'arch'", max_length=32
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "color",
                    models.CharField(
                        help_text="CSS rengi veya değişken adı", max_length=32
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["order", "key"],
                "unique_together": {("user", "key")},
            },
        ),
        migrations.CreateModel(
            name="DeepDive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                (
                    "tagline",
                    models.TextField(
                        blank=True, help_text="Üst kısımdaki kısa açıklama"
                    ),
                ),
                (
                    "overview",
                    models.TextField(
                        blank=True,
                        help_text="Genel bakış paragrafları (boş satırla ayır)",
                    ),
                ),
                (
                    "strategy",
                    models.TextField(blank=True, help_text="Strateji paragrafları"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Düşük"),
                            ("medium", "Orta"),
                            ("high", "Yüksek"),
                        ],
                        default="medium",
                        max_length=8,
                    ),
                ),
                (
                    "meta_pills",
                    models.CharField(
                        blank=True,
                        help_text="Üst-sağ köşedeki etiketler, virgülle ayır (örn '~600 sayfa, 12 bölüm')",
                        max_length=255,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_deep_dives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "slug"],
                "unique_together": {("user", "slug")},
            },
        ),
        migrations.CreateModel(
            name="DeepDiveResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "res_type",
                    models.CharField(
                        help_text="Örn 'Ana kitap', 'Video ders'", max_length=64
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("meta", models.CharField(blank=True, max_length=500)),
                ("link", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "deep_dive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="CareerPath.deepdive",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DeepDiveTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num",
                    models.CharField(
                        help_text="Topic numarası, örn '01'", max_length=8
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sub_title",
                    models.CharField(
                        blank=True, help_text="İsim altındaki açıklama", max_length=255
                    ),
                ),
                (
                    "domain_text",
                    models.TextField(
                        blank=True, help_text="'Senin domain'inde' kolonu"
                    ),
                ),
                (
                    "ai_text",
                    models.TextField(
                        blank=True, help_text="'AI nasıl kullanılır' kolonu"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "deep_dive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="CareerPath.deepdive",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "num"],
                "unique_together": {("deep_dive", "num")},
            },
        ),
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num",
                    models.CharField(help_text="Faz numarası, örn '01'", max_length=8),
                ),
                (
                    "time_range",
                    models.CharField(help_text="Örn '0–3 ay'", max_length=64),
                ),
                (
                    "theme",
                    models.CharField(
                        help_text="Faz teması, örn 'Temel atma'", max_length=128
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_phases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "num"],
                "unique_together": {("user", "num")},
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("book", "Kitap"),
                            ("project", "Proje"),
                            ("cert", "Sertifika"),
                            ("", "Diğer"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "ai_usage",
                    models.TextField(
                        blank=True, help_text="AI nasıl kullanılır kutucuğu"
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="1-5, 5+ yüksek öncelik rozeti"
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="CareerPath.category",
                    ),
                ),
                (
                    "deep_dive",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_tasks",
                        to="CareerPath.deepdive",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="CareerPath.phase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["phase__order", "category__order", "order"],
            },
        ),
        migrations.CreateModel(
            name="TaskResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("meta", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="CareerPath.task",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TopicConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=64)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concepts",
                        to="CareerPath.deepdivetopic",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
