# Generated by Django 6.0.1 on 2026-05-16 21:37

from django.conf import settings
from django.db import migrations, models


def renumber_orders(apps, schema_editor):
    """Phase.order ve Category.order alanlarını kullanıcı başına 0..N-1
    aralığında çakışmasız hale getirir. Mevcut sıralama korunur
    (eşit order'larda ID'ye göre stabil)."""
    Phase = apps.get_model("CareerPath", "Phase")
    Category = apps.get_model("CareerPath", "Category")

    for Model in (Phase, Category):
        user_ids = Model.objects.values_list("user_id", flat=True).distinct()
        for uid in user_ids:
            rows = list(Model.objects.filter(user_id=uid).order_by("order", "id"))
            for idx, row in enumerate(rows):
                if row.order != idx:
                    row.order = idx
                    row.save(update_fields=["order"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("CareerPath", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phase",
            options={"ordering": ["order", "id"]},
        ),
        # Önce yeni alanları ve order'ı değiştir, sonra renumber, EN SON unique_together
        migrations.AddField(
            model_name="phase",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phase",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Matriste satır sırası (kullanıcı bazında benzersiz)",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Matriste kolon sırası (kullanıcı bazında benzersiz)",
            ),
        ),
        # Çakışan order'ları kullanıcı başına 0..N-1 yap (UNIQUE constraint öncesi)
        migrations.RunPython(renumber_orders, noop_reverse),
        # Eski num/time_range kaldır
        migrations.RemoveField(
            model_name="phase",
            name="num",
        ),
        migrations.RemoveField(
            model_name="phase",
            name="time_range",
        ),
        # Unique constraints en sonda
        migrations.AlterUniqueTogether(
            name="phase",
            unique_together={("user", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("user", "key"), ("user", "order")},
        ),
    ]
